## Place holder until "real" java build system

# export $(CLASSPATH)="/usr/share/java/junit:$(CLASSPATH)"

compile:
	javac src/net/is/tree/bstree.java
	javac test/net/is/tree/bstree_test.java

test:
	echo $(CLASSPATH)
	echo $(HOME)


